# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt


build:
  commands:
    # generate API stubs first
    - sphinx-apidoc -f -o docs/api src/ximinf

sphinx:
  configuration: docs/conf.py
