# .readthedocs.yml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  commands:
    - sphinx-apidoc -o docs/api src/my_package

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  install:
   - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py