version: 2

# Build environment
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# Python environment
python:
  install:
    - requirements: docs/requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/conf.py