version: 2

# Build environment
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# Python environment
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Commands to run before building docs
build:
  commands:
    # Regenerate API documentation
    - sphinx-apidoc -o docs/api src/ximinf --separate --force
    # Build the HTML documentation
    - sphinx-build -b html docs docs/_build/html