# .readthedocs.yml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  install:
   - requirements: docs/requirements.txt

build:
  commands:
    # generate API stubs first
    - sphinx-apidoc -f -o docs/api src/ximinf

sphinx:
  configuration: docs/conf.py