version: 2

# Build environment and commands
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    # Install Sphinx and dependencies
    - pip install -r docs/requirements.txt
    # Regenerate API documentation
    - sphinx-apidoc -o docs/api src/ximinf --separate --force
    # Build the HTML documentation
    # - sphinx-build -b html docs docs/_build/html
    - sphinx-build -b html docs $READTHEDOCS_OUTPUT/html

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
