# Simulation libraries
import skysurvey
import numpy as np
from pyDOE import lhs  # LHS sampler
from scipy.special import erfinv, erf
import scipy.special as sci_spe
from modeldag.tools import apply_gaussian_noise
from copy import deepcopy

def get_stretch_mode_simple(x1, x1ref):
    """
    Determine whether each stretch value exceeds its reference value.

    Parameters
    ----------
    x1 : array-like
        Stretch parameter value or array of stretch parameter values.

    x1ref : array-like
        Reference stretch value or array of reference values. Must be
        broadcastable with ``x1``.

    Returns
    -------
    array-like of bool
        Boolean array indicating where ``x1`` is greater than ``x1ref``.
    """
    return x1>x1ref

def scan_params(priors, N, n_realisation=1, dtype=np.float32):
    """
    Generate parameter sets using Latin Hypercube Sampling (LHS).

    Each parameter is sampled independently according to the prior
    distribution specified in ``priors``. The LHS sampling is performed
    in the unit interval and then transformed according to the selected
    prior type.

    Supported prior types are ``"uniform"``, ``"gaussian"``,
    ``"half-gaussian"``, ``"positive-gaussian"``, ``"exponential"``,
    ``"truncated-exponential"``, and ``"log-uniform"``.

    Parameters
    ----------
    priors : dict
        Mapping from parameter names to prior definitions. Each prior
        definition must contain:

        ``"range"``
            Two-element sequence ``(low, high)`` defining the parameter
            range.

        ``"type"``
            String specifying the prior distribution. Supported values are
            ``"uniform"``, ``"gaussian"``, ``"half-gaussian"``,
            ``"positive-gaussian"``, ``"exponential"``,
            ``"truncated-exponential"``, and ``"log-uniform"``.

    N : int
        Number of distinct parameter tuples generated by the Latin
        Hypercube Sampling procedure.

    n_realisation : int, optional
        Number of realizations generated for each parameter tuple.
        Default is 1.

    dtype : data-type, optional
        Numeric data type used for the returned parameter arrays.
        Default is ``np.float32``.

    Returns
    -------
    params_dict : dict
        Dictionary mapping each parameter name to an array of shape
        ``(N * n_realisation,)`` containing the sampled parameter values.

    Raises
    ------
    ValueError
        If a prior has an unsupported type or if the bounds are
        incompatible with the requested prior distribution.

    Notes
    -----
    The Gaussian prior uses the midpoint of the specified range as its
    mean and chooses the standard deviation such that the interval
    corresponds approximately to 95% of the Gaussian probability mass.

    The half-Gaussian prior requires ``low = 0`` and samples the absolute
    value of a zero-centered Gaussian distribution.

    The positive-Gaussian prior uses a Gaussian distribution truncated
    below zero.

    For the exponential and truncated-exponential priors, ``low = 0`` is
    required. The exponential rate parameter is chosen such that 95% of
    the untruncated exponential distribution lies below ``high``.

    The log-uniform prior is sampled uniformly in logarithmic space and
    therefore requires ``low > 0``.
    """
    param_names = list(priors.keys())
    n_params = len(param_names)

    # LHS unit samples in [0,1]
    unit_samples = lhs(n_params, samples=N)  # shape (N, n_params)
    samples = np.zeros_like(unit_samples)

    for i, p in enumerate(param_names):
        u = unit_samples[:, i]
        info = priors[p]
        low, high = info["range"]
        ptype = info["type"]

        if ptype == 'uniform':
            samples[:, i] = u * (high - low) + low
        elif ptype == 'gaussian':
            mu = 0.5 * (low + high)
            sigma = (high - low) / (2.0 * 1.96)
            gaussian = np.sqrt(2.0) * erfinv(2.0 * u - 1.0)
            samples[:, i] = mu + sigma * gaussian
        elif ptype == 'half-gaussian':
            if low != 0:
                raise ValueError(f"Half-Gaussian prior requires low=0, got {low}")
            sigma = high / 1.96
            gaussian = np.sqrt(2.0) * erfinv(2.0 * u - 1.0)
            samples[:, i] = np.abs(gaussian) * sigma
        elif ptype == 'positive-gaussian':
            mu = 0.5 * (low + high)
            sigma = (high - low) / (2.0 * 1.96)

            alpha = (0.0 - mu) / sigma
            Phi_alpha = 0.5 * (1.0 + erf(alpha / np.sqrt(2.0)))

            # Transform uniform samples into truncated normal
            truncated_u = Phi_alpha + u * (1.0 - Phi_alpha)
            gaussian = np.sqrt(2.0) * erfinv(2.0 * truncated_u - 1.0)

            samples[:, i] = mu + sigma * gaussian
        elif ptype == 'exponential':
            if low != 0:
                raise ValueError(f"Exponential prior requires low=0, got {low}")

            # 95% mass below `high`
            lam = -np.log(1.0 - 0.95) / high

            # Standard exponential inverse CDF
            samples[:, i] = -np.log(1.0 - u) / lam

        elif ptype == 'truncated-exponential':
            if low != 0:
                raise ValueError(f"Exponential prior requires low=0, got {low}")

            # Truncate the exponential distribution at `high`
            lam = -np.log(1.0 - 0.95) / high  # Lambda for 95% mass below `high`

            # Inverse CDF for truncated exponential: F^{-1}(u) = -log(1 - u*(1 - exp(-lam*high))) / lam
            # This ensures samples are in [0, high]
            samples[:, i] = -np.log(1.0 - u * (1.0 - np.exp(-lam * high))) / lam
        elif ptype == 'log-uniform':
            if low <= 0:
                raise ValueError(f"log-uniform prior for '{p}' requires low>0")
            samples[:, i] = low * (high / low) ** u
        else:
            raise ValueError(f"Unknown prior type '{ptype}' for parameter '{p}'")

    # Repeat for multiple realizations if needed
    params_dict = {p: np.repeat(samples[:, i], n_realisation).astype(dtype)
                   for i, p in enumerate(param_names)}

    return params_dict

def simulate_one(
    params_dict,
    z_max,
    M,
    cols,
    default_params,
    SIMULATION_MODEL,
    errormodel=None,
    survey_name=None,
    rng=None,
    N=None,
    i=None,
    out_df=False,
):
    """
    Simulate a single dataset of Type Ia supernovae.

    The supplied simulation parameters are merged with the default
    parameters, with values in ``params_dict`` taking precedence. These
    parameters are then used to configure a copy of ``SIMULATION_MODEL``
    before drawing a sample of Type Ia supernovae with ``skysurvey``.

    Optional Gaussian measurement noise can subsequently be applied to the
    simulated data.

    Parameters
    ----------
    params_dict : dict
        Dictionary containing simulation parameters that override the
        corresponding values in ``default_params``. The parameters
        ``"alpha"``, ``"beta"``, ``"mabs"``, ``"gamma"``, and
        ``"sigma_int"`` are used to configure the supernova simulation
        model.

    z_max : float
        Maximum redshift of the simulated supernova sample.

    M : int
        Number of Type Ia supernovae to simulate.

    cols : sequence of str
        Names of the columns to return when ``out_df=False``. Columns that
        are not present in the simulated dataframe are ignored.

    default_params : dict
        Default simulation parameters. Values in ``params_dict`` override
        corresponding entries in this dictionary.

    SIMULATION_MODEL : dict
        Base simulation model configuration passed to
        ``skysurvey.SNeIa.from_draw``. The model is deep-copied before its
        parameter-dependent values are modified.

    errormodel : optional
        Configuration used by ``apply_gaussian_noise`` to add Gaussian
        measurement noise to the simulated data. If ``None``, no additional
        noise is applied.

    rng : numpy.random.Generator, optional
        NumPy random number generator used for the simulation and noise
        generation. If ``None``, a new default generator is created.

    N : int, optional
        Total number of simulations in the surrounding simulation run.
        If provided together with ``i``, progress is periodically printed.

    i : int, optional
        Zero-based index of the current simulation in a larger simulation
        run. Used only for progress reporting when ``N`` is also provided.

    out_df : bool, optional
        If ``True``, return the complete simulated dataframe. If ``False``,
        return only the columns specified by ``cols`` as a dictionary.
        Default is ``False``.

    Returns
    -------
    pandas.DataFrame or dict
        If ``out_df=True``, returns the complete simulated dataframe.

        If ``out_df=False``, returns a dictionary mapping the requested
        column names to lists containing their simulated values.

    Notes
    -----
    A deep copy of ``SIMULATION_MODEL`` is used so that the parameter
    updates performed by this function do not modify the original model
    configuration.

    If the simulation model contains an ``"isup"`` component, its
    ``"func"`` entry is replaced by ``rng.binomial`` so that the supplied
    random-number generator is used for the corresponding sampling.
    """

    # Print progress
    if N is not None and i is not None:
        if (i + 1) % max(1, N // 10) == 0 or i == N - 1:
            print(f"Simulation {i + 1}/{N}", end="\r", flush=True)

    # Merge defaults with provided params
    params = {**default_params, **params_dict}

    if "alpha" in params:
        params["alpha_low"] = params["alpha"]
        params["alpha_high"] = params["alpha"]
    
    # alpha_ = float(params["alpha"])
    alpha_low_ = float(params["alpha_low"])
    alpha_high_ = float(params["alpha_high"])
    beta_ = float(params["beta"])
    mabs_ = float(params["mabs"])
    gamma_ = float(params["gamma"])
    sigma_int_ = float(params["sigma_int"])
    x1_ref_ = float(params["x1_ref"])

    model = deepcopy(SIMULATION_MODEL)

    model["magabs"]["kwargs"]["sigmaint"] = sigma_int_
    model["magabs"]["kwargs"]["mabs"] = mabs_
    model["magabs"]["kwargs"]["alpha_low"] = alpha_low_
    model["magabs"]["kwargs"]["alpha_high"] = alpha_high_
    
    model["magabs"]["kwargs"]["beta"] = beta_

    if "gamma" in model["magabs"]["kwargs"]:
        model["magabs"]["kwargs"]["gamma"] = gamma_

    if "x1_ref" in model["magabs"]["kwargs"]:
        model["magabs"]["kwargs"]["x1_ref"] = x1_ref_

    # Set survey-specific selection parameters
    cut_loc, cut_scale = None, None
    if survey_name is not None:
        cut_loc_key = f"cut_loc_{survey_name}"
        cut_scale_key = f"cut_scale_{survey_name}"
        cut_loc = params[cut_loc_key]
        cut_scale = params[cut_scale_key]

    if rng is None:
        rng = np.random.default_rng()
    
    if "isup" in model:
        model["isup"]["func"] = rng.binomial

    # Draw
    snia = skysurvey.SNeIa.from_draw(
        size=M,
        zmax=z_max,
        model=model,
    )

    # Noise
    if errormodel is None:
        df = snia.data
    else:
        if rng is None:
            rng = np.random.default_rng()
        df = apply_gaussian_noise(errormodel, data=snia.data, rng=rng)

        # Apply malmquist bias (selection) if survey-specific parameters are provided
    if cut_loc is not None and cut_scale is not None:
        mag = np.asarray(df["magobs"], dtype=np.float32)

        # Detection probability
        p_detect = 1.0 - sci_spe.expit((mag - cut_loc) * cut_scale)

        # Bernoulli draw handled by numpy
        mask = np.random.binomial(1, p_detect).astype(bool)

        df = df.loc[mask].reset_index(drop=True)

    if out_df:
        return df

    result = {
        col: df[col].to_numpy(copy=False)
        for col in cols
        if col in df
    }

    del df
    return result
    

# def simulate_one(params_dict, z_max, M, cols, default_params, c=None, errormodel=None, rng=None, simple_broken = False, N=None, i=None, survey_name=None, lightcurve=False):
#     # Print progress
#     if N is not None and i is not None:
#         if (i+1) % max(1, N//10) == 0 or i == N-1:
#             print(f"Simulation {i+1}/{N}", end="\r", flush=True)

#     # Merge defaults with provided params (params_dict takes priority)
#     params = {**default_params, **params_dict}

#     # If a single alpha is provided, enforce alpha_low = alpha_high = alpha
#     if "alpha" in params:
#         params["alpha_low"] = params["alpha"]
#         params["alpha_high"] = params["alpha"]

#     # Ensure all are floats
#     alpha_low_ = float(params["alpha_low"])
#     alpha_high_ = float(params["alpha_high"])
#     beta_  = float(params["beta"])
#     mabs_  = float(params["mabs"])
#     gamma_ = float(params["gamma"])
#     sigma_int_ = float(params["sigma_int"])
#     x1_ref_ = float(params["x1_ref"])

#     # Set survey-specific selection parameters
#     cut_loc, cut_scale = None, None
#     if survey_name is not None:
#         cut_loc_key = f"cut_loc_{survey_name}"
#         cut_scale_key = f"cut_scale_{survey_name}"
#         cut_loc = params[cut_loc_key]
#         cut_scale = params[cut_scale_key]

#     if "Om0" in params:
#         Om0 = params["Om0"]
#         Ob0 = fb * Om0
#         cosmo = FlatLambdaCDM(
#             **(Planck18.parameters | {"Om0": Om0, "Ob0": Ob0})
#         )
#     else:
#         cosmo = FlatLambdaCDM(**(Planck18.parameters))

#     brokenalpha_model = skysurvey_sniapop.brokenalpha_model

#     if c is None:
#         c = { "func": stats.alpha.rvs, "kwargs":{"a":3.63, "loc": -0.416, "scale": 1.62}}

#     if simple_broken == True:
#         brokenalpha_model['x1'] = {'func': SNeIaStretch.nicolas2021}
#         brokenalpha_model['x1mode'] = {'func': get_strect_mode_simple, 'kwargs': {'x1': '@x1', 'x1ref': x1_ref_}}

#         # Generate SNe sample
#         snia = skysurvey.SNeIa.from_draw(
#             # tstart=survey.date_range[0],
#             # tstop=survey.date_range[1],
#             size=M,
#             zmax=z_max,
#             model=brokenalpha_model,
#             magabs={
#                 "x1": "@x1",
#                 "c": c,
#                 "mabs": mabs_,
#                 "sigmaint": sigma_int_,
#                 "alpha_low": alpha_low_,
#                 "alpha_high": alpha_high_,
#                 "beta": beta_,
#                 "gamma": gamma_,
#             },
#             magobs={
#                 'cosmology': cosmo
#             }
#         )
#     else:
#         # Generate SNe sample
#         snia = skysurvey.SNeIa.from_draw(
#             # tstart=survey.date_range[0],
#             # tstop=survey.date_range[1],
#             size=M,
#             zmax=z_max,
#             model=brokenalpha_model,
#             magabs={
#                 "x1": "@x1",
#                 "c": "@c",
#                 "mabs": mabs_,
#                 "sigmaint": sigma_int_,
#                 "alpha_low": alpha_low_,
#                 "alpha_high": alpha_high_,
#                 "beta": beta_,
#                 "gamma": gamma_,
#                 "x1ref": x1_ref_
#             },
#             magobs={
#                 'cosmology': cosmo
#             }
#         )

#     # Apply noise
#     if errormodel is None:
#         df = snia.data
#     else:
#         if rng is None:
#             rng = np.random.default_rng()
#         noisy_snia = apply_gaussian_noise(errormodel, data=snia.data, rng=rng)
#         df = noisy_snia

#     # Apply malmquist bias (selection) if survey-specific parameters are provided
#     if cut_loc is not None and cut_scale is not None:
#         mag = np.asarray(df["magobs"], dtype=np.float32)

#         # Detection probability
#         p_detect = 1.0 - expit((mag - cut_loc) * cut_scale)

#         # Bernoulli draw handled by numpy
#         mask = np.random.binomial(1, p_detect).astype(bool)

#         df = df.loc[mask].reset_index(drop=True)

#     # Collect columns
#     data_dict = {col: list(df[col]) for col in cols if col in df}
#     return data_dict